phases:
  install:
    runtime-versions:
       docker: 18
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t machineinfodemo ."	 
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push abhishekmhadocker/machineinfodemo:v1.1.1"
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"abhishekmhadocker\" --password=\"abhishek55@\""
version: 0.2
