phases:
 install:
    runtime-versions:
      docker: 18
 pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - "$(aws ecr get-login --no-include-email --region us-east-1)" 
 build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t cybage_ctg_devops_machineinfo_codebuild_abhishek . "
      - "docker tag cybage_ctg_devops_machineinfo_codebuild_abhishek 543816070942.dkr.ecr.us-east-1.amazonaws.com/cybage_ctg_devops_machineinfo_codebuild_abhishek:v1.0.0"
 post_build:
    commands:
       - "docker push 543816070942.dkr.ecr.us-east-1.amazonaws.com/cybage_ctg_devops_machineinfo_codebuild_abhishek:v1.0.0"
 
version: 0.2
